-- CreateTable
CREATE TABLE "Margin" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "state" INTEGER NOT NULL DEFAULT 0,
    "county" INTEGER NOT NULL DEFAULT 0,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
